name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Playwright Docker image
        run: docker pull mcr.microsoft.com/playwright:v1.44.0-focal

      - name: Run tests in Playwright Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            mcr.microsoft.com/playwright:v1.44.0-focal \
            bash -c "npm ci && npx playwright install --with-deps && npx playwright test"
