name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Playwright Docker image v1.54.1
        run: docker pull mcr.microsoft.com/playwright:v1.54.1-noble

      - name: Run tests in Playwright Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -w /app \
            mcr.microsoft.com/playwright:v1.54.1-noble \
            bash -c "npm ci && npx playwright install chromium && npx playwright test --reporter=html --reporter=list --quiet"

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
